// Generated by CoffeeScript 1.7.1
(function () {
    var FacebookStrategy, LocalStrategy, User, Utils, async, hash, localStrategy, passport;

    async = require('async');

    hash = require('../utils/pass').hash;

    Utils = require('../utils/utils').Utils;

    passport = require("passport");

    LocalStrategy = require('passport-local').Strategy;

    FacebookStrategy = require('passport-facebook').Strategy;

    var Driver = require('./user').User;


    /*
     PassPort Setttings
     */

    localStrategy = new LocalStrategy({
        usernameField: 'username',
        passReqToCallback: true
    }, function (req, username, password, done) {
        var siteId;
        siteId = req.body.siteId || '0';

        Driver.authenticateDriver(siteId, username, password, done);
    });

    var managerStrategy = new LocalStrategy({
        usernameField: 'username',
        passReqToCallback: true
    }, function (req, username, password, done) {
        console.log('managerStrategy');
        var siteId;
        siteId = req.body.siteId || '0';
        Driver.managerLogin(siteId, username, password, done);
    });

    passport.use('driver-local', localStrategy);
    passport.use('manager-local', managerStrategy);

    passport.use(new FacebookStrategy({
        clientID: "YOUR ID",
        clientSecret: "YOUR CODE",
        callbackURL: "http://localhost:3000/auth/facebook/callback"
    }, function (accessToken, refreshToken, profile, done) {
        Driver.authenticateFb(accessToken, refreshToken, profile, done);
    }));

    passport.serializeUser(function (user, done) {
        done(null, user.id);
    });

    passport.deserializeUser(function (id, done) {
        Driver.deserializeUser(id, done);
    });

    exports.Driver = Driver;

    exports.passport = passport;

}).call(this);

//# sourceMappingURL=component.map
